Repository insightsengineering/scda.2022, pull requests merged in 2022-10, with the labels that each got.

#76 75 Clean up `scda.2022` NEWS
  NEWS.md
Labels: sme

#80 77 Initialize `2022_10_13` datasets
  DESCRIPTION
  NEWS.md
  R/data.R
  R/data_2022_10_13.R
  data/rcd_2022_10_13.RData
  data/rcd_2022_10_13_adab.RData
  data/rcd_2022_10_13_adae.RData
  data/rcd_2022_10_13_adaette.RData
  data/rcd_2022_10_13_adcm.RData
  data/rcd_2022_10_13_addv.RData
  data/rcd_2022_10_13_adeg.RData
  data/rcd_2022_10_13_adex.RData
  data/rcd_2022_10_13_adhy.RData
  data/rcd_2022_10_13_adlb.RData
  data/rcd_2022_10_13_admh.RData
  data/rcd_2022_10_13_adpc.RData
  data/rcd_2022_10_13_adpp.RData
  data/rcd_2022_10_13_adqs.RData
  data/rcd_2022_10_13_adrs.RData
  data/rcd_2022_10_13_adsl.RData
  data/rcd_2022_10_13_adsub.RData
  data/rcd_2022_10_13_adtr.RData
  data/rcd_2022_10_13_adtte.RData
  data/rcd_2022_10_13_advs.RData
  data_raw/rcd.R
  man/rcd_data_2022.Rd
  man/rcd_data_2022_10_13.Rd
Labels: sme

#79 add goshawk
  staged_dependencies.yaml
Labels: core

#81 add teal.goshawk
  staged_dependencies.yaml
Labels: core

#87 add new packages to staged deps
  staged_dependencies.yaml
Labels: blocked, core, sme

#89 update scda.2022 for teal and chevron
  staged_dependencies.yaml
Labels: blocked, core, sme
